import type { Lang } from "../components/wird-store";

const AR: Record<string, string> = {
  "app.tag": "وِرد",
  "nav.today": "اليوم",
  "nav.calendar": "التقويم",
  "nav.insights": "التقدّم",
  "nav.review": "الحصاد",
  "nav.library": "الأذكار",
  "nav.account": "حسابي",
  "side.streak": "٣ أيام متتالية",
  "side.streakSub": "واصل هذا النور",
  "side.profileSub": "الحمدلله دائمًا",
  "header.newDay": "يوم جديد",
  "header.greet": "صباح النور، محمد",
  "header.sub": "كل خطوة صغيرة تقرّبك. جعل الله يومك عامرًا بذكره.",
  "header.today": "اليوم",
  "header.voice": "تسجيل صوتي",
  "header.heardFail": "لم أسمع شيئًا — حاول مجددًا",
  "header.heardTry": "سمعت: «{t}» — جرّب: سجلت الفجر",
  "header.heardOk": "✓ سُجّل: {t}",
  "hero.pill": "رحلتك اليوم · يوم {mode}",
  "hero.title": "أنت تصنع أثرًا جميلًا",
  "hero.progress": "أكملت {c} من {t} وردًا اليوم. استمر، فالقليل الدائم أحبّ إلى الله.",
  "hero.pct": "إنجاز اليوم",
  "hero.points": "نقطة بركة",
  "hero.done": "مكتمل",
  "mode.full": "كامل",
  "mode.normal": "عادي",
  "mode.busy": "مشغول",
  "mode.travel": "سفر",
  "mode.sick": "مرض",
  "mode.title": "كيف يبدو يومك؟",
  "mode.sub": "اختر ما يناسب قدرتك اليوم.",
  "mode.focus": "◉ تركيز",
  "focus.quit": "× إنهاء التركيز",
  "focus.eyebrow": "لحظة واحدة تكفي",
  "focus.q": "هل أوترت اليوم؟",
  "focus.sub": "ركعة واحدة قد تكون أجمل ختام ليومك.",
  "focus.logged": "✓ تم تسجيل الوتر",
  "focus.cta": "سجّل الوتر الآن",
  "tools.now": "الآن",
  "tools.nowSub": "ما يناسب وقتك",
  "tools.min": "أقل ورد لليوم",
  "tools.minSub": "أساسيات بلا ضغط",
  "tools.start": "ابدأ من الآن",
  "tools.startSub": "ما زال في اليوم خير",
  "tools.custom": "عبادة مخصصة",
  "tools.customSub": "أضف ما يناسبك",
  "tools.customAsk": "اسم العبادة المخصصة:",
  "rescue.eyebrow": "خطة إنقاذ اليوم",
  "rescue.title": "خطوة صغيرة، وأثرها كبير",
  "rescue.sub": "لا تحتاج أن تنجز كل شيء. اختر ما يناسبك الآن.",
  "rescue.one": "عبادة واحدة الآن",
  "rescue.oneTitle": "أذكار الصباح",
  "rescue.oneSub": "دقيقتان تضيئان بداية يومك.",
  "rescue.oneDone": "✓ تم تسجيلها",
  "rescue.oneGo": "ابدأ الآن ←",
  "rescue.quran": "جلسة قرآن",
  "rescue.quranPages": " · {n} صفحات اليوم",
  "rescue.quranDone": "أحسنت، انتهت الجلسة",
  "rescue.quranStart": "ابدأ جلسة قرآن",
  "rescue.quranAsk": "كم صفحة قرأت؟",
  "rescue.quranLive": "الجلسة مستمرة",
  "rescue.quranBegin": "ابدأ الجلسة",
  "rescue.min": " د",
  "rescue.focusBtn": "وضع تركيز حتى الصلاة",
  "rescue.record": "سجل الصلاة",
  "rescue.recorded": "✓ سُجّلت",
  "rescue.prep": "الاستعداد للصلاة",
  "rescue.prepSub": "بقي ٢٠ دقيقة على العصر · هل تريد الوضوء؟",
  "ramp.eyebrow": "ورد متدرج",
  "ramp.full": "الأسبوع الثاني · صفحتان يوميًا",
  "ramp.light": "الوضع المخفف · صفحة واحدة يوميًا",
  "ramp.sub": "تقدّمك هادئ وثابت. يمكنك التوقف أو تقليل الهدف متى شئت.",
  "ramp.ease": "خفّف الورد",
  "ramp.restore": "أعد الورد",
  "intent.eyebrow": "قبل العمل أو الدراسة",
  "intent.q": "ما نيتك الآن؟",
  "intent.edit": "تعديل النية",
  "intent.ask": "ما نيتك اليوم؟",
  "intent.job": "طلب الرزق الحلال",
  "intent.craft": "إتقان العمل",
  "intent.benefit": "نفع الناس",
  "intent.learn": "التعلم",
  "intent.family": "إعانة الأسرة",
  "friday.eyebrow": "رفيق الجمعة",
  "friday.soon": "· خطتك القادمة",
  "friday.now": "· اليوم",
  "friday.titleSoon": "ورد الجمعة بانتظارك",
  "friday.titleNow": "جمعة مباركة، وردك ينتظرك",
  "util.fav": "مفضلة المستخدم",
  "util.forget": "لا تنسَ",
  "util.tawbah": "دفتر التوبة والاستغفار",
  "util.tawbahNeed": "أحتاج إلى استغفار اليوم",
  "util.tawbahDone": "✓ تم",
  "util.tawbahGo": "سجّلها لنفسك",
  "moment.next": "الصلاة القادمة",
  "moment.setTimes": "اضبط مواقيتك",
  "moment.setTimesSub": "من صفحة حسابي ← مواقيت الصلاة",
  "moment.remind": "تنبيه قبل الأذان",
  "moment.remindOn": "✓ سيتم تنبيهك",
  "moment.mosque": "🕌",
  "moment.mosqueTitle": "وضع المسجد: يكتم التذكيرات",
  "moment.niyyah": "نية اليوم",
  "tasbeeh.title": "عداد الذكر السريع",
  "tasbeeh.done": "✓ اكتمل",
  "sec.dailyEyebrow": "وردك اليومي",
  "sec.daily": "الصلوات والأوراد",
  "filter.all": "⌄ الكل",
  "filter.done": "✓ المكتمل",
  "filter.todo": "○ المتبقي",
  "sec.extrasEyebrow": "أكثر من الصلاة",
  "sec.extras": "ورد القرآن والخير",
  "sec.moreDetail": "عمل يسير وأثر كبير",
  "quran.eyebrow": "ورد القرآن اليومي",
  "quran.of": "من",
  "quran.page": "صفحة",
  "quran.full": "ما شاء الله، أتممت وردك اليوم. زد ما شئت.",
  "quran.next": "خطوتك القادمة: أكمل {n} صفحات.",
  "quran.add": "أضف صفحة +",
  "quran.plan": "عرض خطتي",
  "adhkar.eyebrow": "أذكار متنوعة",
  "adhkar.title": "اذكر الله في تفاصيل يومك",
  "adhkar.sub": "أدعية قصيرة تُعينك على حضور القلب في كل لحظة.",
  "dua.eyebrow": "مساحتك الخاصة",
  "dua.title": "دعائي اليوم",
  "dua.add": "+ أضف دعاءً من قلبك",
  "dua.ask": "اكتب دعاءً من قلبك:",
  "dua.rE": "دعاؤك اليوم",
  "dua.rT": "اللهم ارزق والديّ الصحة والعافية",
  "dua.rS": "دعاء للوالدين",
  "dua.rB": "دعوت به اليوم",
  "dua.rDone": "✓ دعوت به اليوم",
  "gentle.eyebrow": "تذكير لطيف",
  "gentle.title": "كل يوم بداية جديدة",
  "gentle.sub": "فاتك شيء؟ لا بأس. اختر عملًا صغيرًا الآن، والله يحب العمل الدائم ولو كان قليلًا.",
  "gentle.week": "هذا الأسبوع",
  "gentle.witr": "الوتر ٥ أيام",
  "goals.eyebrow": "أهدافك على مهل",
  "goals.title": "رحلتك الروحية",
  "goals.add": "+ أضف هدفًا",
  "goals.ask": "اسم الهدف الجديد:",
  "goals.newDetail": "هدف جديد · ابدأ بخطوة صغيرة",
  "goals.new": "جديد",
  "goals.witr": "الوتر هذا الأسبوع",
  "goals.witrSub": "بقي ٣ أيام لإكمال هدفك",
  "goals.quran": "ورد القرآن الشهري",
  "goals.quranSub": "٢٤ صفحة من ٦٠",
  "goals.kin": "صلة الرحم",
  "goals.kinSub": "هدف أسبوعي لطيف",
  "night.eyebrow": "قبل النوم",
  "night.title": "اختتم يومك بسكينة",
  "night.sub": "وضوء، أذكار النوم، آية الكرسي، نعمة تشكر الله عليها، ثم نية للفجر.",
  "night.cta": "ابدأ روتين الليل ←",
  "night.journalEyebrow": "محاسبة خاصة",
  "night.journalQ": "ما أجمل شيء فعلته اليوم؟",
  "night.journalPh": "اكتب لنفسك كلمة طيبة…",
  "night.journalNote": "هذه المساحة لك وحدك، ولا تدخل في الإحصاءات.",
  "footer.verse": "﴿ وَاذْكُر رَّبَّكَ كَثِيرًا وَسَبِّحْ بِالْعَشِيِّ وَالْإِبْكَارِ ﴾",
  "minplan.title": "خطة الحد الأدنى مفعّلة",
  "minplan.sub": "الصلوات، ذكر قصير، آية واحدة، استغفار ١٠ مرات، والوتر. هذا يكفي لليوم.",
  "minplan.cancel": "إلغاء",
  "now.eyebrow": "ما يناسب وقتك الآن",
  "now.title": "بعد الفجر، بداية مباركة",
  "now.sub": "أربع خطوات فقط. خذ منها ما تيسر لك.",
  "now.done": "✅ تم",
  "now.partial": "◐ جزئيًا",
  "now.later": "↷ لاحقًا",
  "now.foot": "ما زال في اليوم خير كثير.",
  "now.add": "+ أضف عبادة",
  "zk.title": "اذكر الله",
  "zk.close": "إغلاق",
  "ac.account": "حسابي",
  "ac.niyyah": "نيّتي لهذا الأسبوع",
  "ac.customize": "تخصيص عباداتي",
  "ac.qiyam": "وضع قيام الليل",
  "ac.remind": "تذكيرات رحيمة",
  "ac.privacy": "خصوصيتي وبياناتي",
  "ac.newdayT": "يوم جديد، بداية جديدة",
  "ac.newdayS": "يمكنك بدء صفحة جديدة بلطف متى احتجت.",
  "ac.newdayB": "يوم جديد",
  "bk.t": "النسخ الاحتياطي والخصوصية",
  "bk.s": "بياناتك على جهازك فقط — لا خوادم ولا حسابات. صدّر نسخة مشفرة أو استعدها في أي وقت.",
  "bk.enc": "تصدير مشفر",
  "bk.plain": "تصدير عادي",
  "bk.imp": "استيراد",
  "bk.wipe": "مسح الكل",
  "bk.passAsk": "كلمة سر التشفير (احفظها — لا يمكن الاستعادة بدونها):",
  "bk.impAsk": "كلمة سر النسخة المشفرة:",
  "bk.wipeAsk": "مسح كل بيانات ورد من هذا الجهاز نهائيًا؟",
  "bk.count": "تم التصدير ({n} عنصرًا). احفظ الملف في مكان آمن.",
  "bk.okEnc": "تم تصدير نسخة مشفرة (AES-GCM).",
  "bk.restored": "تمت الاستعادة ({n} عنصرًا). حدّث الصفحة لرؤية بياناتك.",
  "bk.bad": "ملف غير صالح أو كلمة سر خاطئة.",
  "bk.fail": "تعذر التصدير. تحقق من مساحة التخزين.",
  "bk.noenc": "تعذر التشفير على هذا المتصفح.",
  "bk.wiped": "مُسحت كل البيانات. حدّث الصفحة للبدء من جديد.",
  "bk.wipeFail": "تعذر المسح.",
  "rm.t": "التذكيرات المحلية",
  "rm.s": "تعمل على جهازك فقط — بلا خوادم. تُكتم تلقائيًا في وضع المسجد.",
  "rm.on": "✓ مفعّلة",
  "rm.off": "تفعيل",
  "rm.bed": "الحصاد",
  "rm.gentle": "لطيف",
  "rm.bal": "متوازن",
  "rm.strict": "صارم",
  "rm.test": "تجربة",
  "rm.testT": "تجربة ناجحة 🔔",
  "rm.testB": "هكذا ستصلك تذكيرات وردك.",
  "rm.sent": "أُرسل إشعار تجريبي.",
  "rm.noperm": "فعّل إذن الإشعارات من المتصفح أولًا.",
  "pt.t": "مواقيت الصلاة (يدوي)",
  "pt.s": "تُستخدم للعد التنازلي وترتيب البطاقات الذكي. اتركها فارغة للوضع الحالي.",
  "ap.t": "المظهر واللغة",
  "ap.s": "اختر مظهرك ولغتك — تُحفظ على جهازك.",
  "ap.light": "فاتح",
  "ap.dark": "ليلي",
  "ap.oled": "أسود",
  "rv.heroE": "حصاد اليوم · دقيقة واحدة قبل النوم",
  "rv.heroT": "ماذا فعلت اليوم؟",
  "rv.heroS": "كل ما سجلته موجود مسبقًا — أكّد ما تم، وصحح ما فات.",
  "rv.heartE": "مراجعة القلب",
  "rv.heartT": "كيف عشت يومك؟",
  "rv.r1": "ملكت غضبي اليوم",
  "rv.r2": "حفظت لساني من الغيبة",
  "rv.r3": "بررت والديّ (اتصال/زيارة/دعاء)",
  "rv.r4": "صدقت في عملي وكلامي",
  "rv.r5": "فعلت إحسانًا (صدقة/مساعدة)",
  "rv.r6": "نمت مبكرًا بنية الفجر",
  "rv.mGood": "مشرق",
  "rv.mOk": "عادي",
  "rv.mLow": "متعب",
  "rv.gratPh": "نعمة واحدة تشكر الله عليها اليوم…",
  "rv.gratAria": "نعمة اليوم",
  "rv.submit": "اختم يومك 🌙",
  "rv.score": "درجتك",
  "rv.pts": "نقطة",
  "rv.edit": "مراجعة اليوم مرة أخرى",
  "rv.stDone": "✓ تم",
  "rv.stPart": "◐ جزئي",
  "rv.stMiss": "○ فات",
  "rv.g85": "يوم مشرق 🌟",
  "rv.g60": "يوم ثابت 🤍",
  "rv.gLow": "تقبل الله 🤲",
  "rv.pagesT": "ورد القرآن",
  "rv.pagesD": "{p} من {g} صفحة",
  "rv.fastT": "الصيام",
  "rv.fastOn": "{f}",
  "rv.fastOff": "لست صائمًا",
  "rv.tasT": "الذكر السريع",
  "nw.i1t": "صلاة الفجر",
  "nw.i1d": "في وقتها · جماعة",
  "nw.i2t": "أذكار بعد الصلاة",
  "nw.i2d": "دقيقتان بهدوء",
  "nw.i3t": "أذكار الصباح",
  "nw.i3d": "٦ من ١٠",
  "nw.i4t": "ورد القرآن",
  "nw.i4d": "صفحتان من ٤",
  "du.feat": "“اللهم أعنّي على ذكرك وشكرك وحسن عبادتك.”",
  "ins.heroE": "تقدّمك من بياناتك — لا تخمين",
  "ins.heroT": "خطواتك الهادئة تصنع أثرًا",
  "ins.heroS": "اختر الفترة التي تود أن تتأملها، بلا مقارنة ولا لوم.",
  "ins.p0": "اليوم",
  "ins.p1": "آخر ٧ أيام",
  "ins.p2": "أسبوعان",
  "ins.p3": "الشهر الحالي",
  "ins.p4": "٣ أشهر",
  "ins.p5": "الموسم",
  "ins.p6": "السنة",
  "ins.avg": "متوسط إنجازك",
  "ins.avgS": "في الفترة المختارة",
  "ins.witr": "ليالي الوتر",
  "ins.witrS": "عادة ثابتة وجميلة",
  "ins.pages": "صفحة قرآن",
  "ins.pagesS": "مجموع الفترة",
  "ins.streak": "سلسلة الالتزام",
  "ins.streakS": "يومًا متتاليًا",
  "ins.coach": "مدربك الخاص ✦",
  "ins.warm": "سجّل أيامًا أكثر ليبدأ التحليل الخبير — نحتاج ١٤ يومًا على الأقل.",
  "ins.chartE": "نظرة على الفترة",
  "ins.chartT": "إنجازك اليومي",
  "ins.chartEmpty": "لا بيانات بعد — ابدأ التسجيل اليوم.",
  "ins.radarE": "توازن الأسبوع",
  "ins.radarT": "أين يقف كل باب؟",
  "ins.stripT": "آخر ٣٠ يومًا",
  "yr.title": "حصاد العام الهجري",
  "yr.days": "يوم نشط",
  "yr.pages": "صفحة",
  "yr.score": "متوسط الدرجات",
  "yr.witr": "ليلة وتر",
  "yr.best": "أفضل شهر",
  "yr.streak": "أطول سلسلة",
  "ins.noData": "لا بيانات",
  "ins.week": "أسبوع",
  "cat.salah": "صلاة",
  "cat.quran": "قرآن",
  "cat.dhikr": "ذكر",
  "cat.knowledge": "علم",
  "cat.character": "خلق",
  "cat.family": "أسرة",
  "br.risk": "معرّض الليلة",
  "br.neglect": "فات {n} أيام متتالية",
  "br.pace": "سرعة القرآن نزلت {d}٪ ({n} مقابل {p} صفحة/يوم)",
  "br.liftA": "أيام",
  "br.liftB": "ترفع بقية يومك +{n}",
  "br.protect": "احمِ هذه أولًا",
  "cal.title": "تقويم رحلتك الهادئة",
  "cal.sub": "اضغط على أي يوم لتتذكر ما أنجزته فيه.",
  "cal.excellent": "إنجاز ممتاز",
  "cal.good": "إنجاز جيد",
  "cal.partial": "إنجاز جزئي",
  "cal.season": "مناسبة",
  "cal.fridayNote": "الجمعة القادمة",
  "cal.fridaySub": "سورة الكهف • الصلاة على النبي ﷺ • التبكير للصلاة",
  "cal.add": "أضف لخطة الجمعة",
  "cal.added": "✓ أُضيفت للخطة",
  "cal.dayNote": "يوم {d}: سجّل وردك من صفحة اليوم، وسيُحفظ تقدمك هنا.",
  "cal.white": "أيام بيض",
  "cal.friday": "جمعة",
  "lb.adhkar": "الأذكار",
  "lb.quran": "القرآن",
  "lb.hadith": "الحديث",
  "lb.paths": "مسارات العلم",
  "lb.dreams": "الأحلام",
  "qr.search": "ابحث في الآيات أو السور…",
  "qr.searchAria": "البحث في القرآن",
  "qr.fontDown": "تصغير الخط",
  "qr.fontUp": "تكبير الخط",
  "qr.noRes": "لا نتائج — جرّب كلمة أخرى.",
  "qr.surahAria": "اختر السورة",
  "qr.mark": "علّم هنا",
  "qr.mem": "حفظ",
  "qr.markLine": "علامتك",
  "qr.memCount": "محفوظ",
  "qr.loading": "جارٍ فتح المصحف…",
  "qr.failT": "تعذر تحميل المصحف",
  "qr.failS": "تحقق من الاتصال أول مرة — يُحفظ بعدها للاستعمال دون إنترنت.",
  "qr.retry": "إعادة المحاولة",
  "hd.search": "ابحث في المختارات…",
  "hd.searchAria": "البحث في الحديث",
  "hd.noRes": "لا نتائج — جرّب كلمة أخرى.",
  "hd.nawawi": "الأربعون النووية",
  "hd.nawawiNote": "مختارات من الأربعين — جوامع الكلم للحفظ والعمل.",
  "hd.fav": "★ المفضلة",
  "hd.favEmpty": "لا مفضلات بعد — اضغط ☆ على أي حديث.",
  "hd.curated": "مختارات مشهورة؛ للنص الكامل راجع النسخ المعتمدة.",
  "hd.favAria": "مفضلة",
  "pa.add": "أضف كتابك الخاص",
  "pa.ask": "اسم الكتاب الذي تقرؤه:",
  "pa.mine": "كتابك الخاص",
  "dr.empty": "لا أحلام مسجلة بعد. الحلم الكبير يبدأ بخطوة صغيرة اليوم.",
  "dr.add": "سجّل حلمك",
  "dr.new": "+ حلم جديد",
  "dr.askT": "حلمك الكبير؟ (مثال: حج ٢٠٢٨، حفظ البقرة)",
  "dr.askTar": "الموعد المستهدف؟ (مثال: رمضان ١٤٤٨)",
  "dr.askStep": "الخطوة التالية؟",
  "dr.askFirst": "أول خطوة صغيرة اليوم؟ (مثال: صفحتان يوميًا)",
  "dr.del": "حذف هذا الحلم؟",
  "dr.delAria": "حذف الحلم",
  "dr.stepNew": "+ خطوة جديدة",
  "ret.absent": "اشتقنا إليك · غبت {n} أيام",
  "ret.title": "الباب مفتوح — ارجع الآن",
  "ret.back": "ابدأ من جديد 🤍",
  "ret.continue": "أكمل يومك عادي",
  "kd.title": "ركن الصغار",
  "kd.emptyT": "تحديات ممتعة لأبنائك",
  "kd.emptyS": "٥ مهام يومية بالنجوم — سجّل اسم الصغير وابدأ.",
  "kd.add": "أضف صغيرًا",
  "kd.ask": "اسم الصغير؟",
  "kd.q1": "صلاة الفجر",
  "kd.q2": "صفحة قرآن",
  "kd.q3": "٣٣ تسبيحة",
  "kd.q4": "عمل طيب",
  "kd.q5": "نوم مبكر",
  "pg.add": "+ عهد جديد",
  "pg.askT": "عهدك؟ (مثال: الفجر في المسجد ٧ أيام)",
  "pg.askS": "الجزاء عند التقصير؟ (مثال: ٥ صدقة)",
  "pg.del": "حذف هذا العهد؟",
  "pg.delAria": "حذف العهد",
  "pg.stake": "الجزاء",
  "pg.days": "يوم وفاء",
  "pg.checkAria": "وفاء اليوم",
  "qd.title": "قضاء الفوائت",
  "qd.empty": "لا فوائت — ما شاء الله",
  "qd.open": "عليك {n} صلوات",
  "qd.clear": "قضيتها ✓",
  "qd.clearDone": "مسح المقضية",
  "qd.delAria": "حذف",
  "fs.title": "صيام اليوم",
  "fs.off": "لست صائمًا اليوم",
  "fs.t0": "فرض رمضان",
  "fs.t1": "نافلة",
  "fs.t2": "قضاء",
  "fs.t3": "أيام بيض",
  "fs.t4": "نذر/كفارة",
  "br.title": "كسر عادة سيئة",
  "br.pick": "اختر عادة تتوب منها اليوم",
  "br.start": "+ ابدأ التحدي",
  "br.clean": "يوم نظيف 🔥",
  "br.slips": "زلّات مسجلة",
  "br.log": "سجل زلة (واستغفر)",
  "br.end": "إنهاء",
  "br.ask": "ما العادة التي تريد كسرها؟",
  "br.delAsk": "حذف تحدي كسر العادة؟",
  "ch.new": "+ تحدٍ جديد",
  "ch.askT": "اسم التحدي (مثال: الفجر ٣٠ يومًا):",
  "ch.askD": "عدد الأيام (مثال: ٣٠):",
  "ch.del": "حذف هذا التحدي؟",
  "ch.delAria": "حذف التحدي",
  "ch.checkAria": "تسجيل اليوم",
  "ch.days": "يوم",
  "rm2.title": "رمضان كريم — تقبل الله طاعتكم",
  "rm2.sub": "التراويح والقيام في انتظارك الليلة.",
  "rm2.tr": "سجل التراويح",
  "rm2.trDone": "✓ صليت التراويح",
  "rm2.fast": "صائم اليوم",
  "ad.g1t": "الصباح",
  "ad.g1d": "ابدأ يومك بسكينة",
  "ad.g2t": "بعد الصلاة",
  "ad.g2d": "أذكار قصيرة بعد كل فريضة",
  "ad.g3t": "المساء والنوم",
  "ad.g3d": "اختم يومك بالطمأنينة",
  "ad.g4t": "المواقف اليومية",
  "ad.g4d": "سفر، طعام، مسجد، منزل",
  "ad.heroE": "أذكار في وقتها",
  "ad.heroT": "اذكر الله في تفاصيل يومك",
  "ad.heroS": "اختر ذكرًا يناسب لحظتك، واحفظ ما تحب العودة إليه.",
  "ad.cfE": "ورد اليوم",
  "ad.cfT": "الصلاة على النبي ﷺ",
  "ad.cfS": "١٠٠ مرة • اجعلها رفيقة يومك",
  "ad.cfDone": "تم الورد · ابدأ من جديد",
  "ad.cfGo": "ابدأ العدّاد",
  "cm.del": "حذف؟",
  "dm.t": "وضع العرض",
  "dm.s": "املأ التطبيق بـ ٤٥ يومًا من البيانات التجريبية لترى الإحصاءات والمدرب يعملان فورًا.",
  "dm.seed": "تعبئة تجريبية",
  "dm.clear": "مسح التجريبية",
  "dm.ok": "تمت تعبئة {n} يومًا. حدّث الصفحة.",
  "dm.cleared": "مُسحت بيانات العرض.",
  "dm.warn": "لن تمس بياناتك الحالية — تُضاف الأيام الفارغة فقط.",
  "ins.share": "مشاركة تقدمي",
  "ins.shared": "تمت المشاركة ✓",
  "ins.downloaded": "حُفظت الصورة ✓",
  "ins.shareFail": "تعذرت المشاركة",
  "pwa.install": "تثبيت التطبيق",
};

const EN: Record<string, string> = {
  "app.tag": "Wird",
  "nav.today": "Today",
  "nav.calendar": "Calendar",
  "nav.insights": "Progress",
  "nav.review": "Review",
  "nav.library": "Adhkar",
  "nav.account": "Account",
  "side.streak": "3-day streak",
  "side.streakSub": "Keep the light going",
  "side.profileSub": "Alhamdulillah always",
  "header.newDay": "A new day",
  "header.greet": "Good morning, Mohamed",
  "header.sub": "Every small step brings you closer.",
  "header.today": "Today",
  "header.voice": "Voice log",
  "header.heardFail": "Didn't catch that — try again",
  "header.heardTry": "Heard: “{t}” — try: Fajr done",
  "header.heardOk": "✓ Logged: {t}",
  "hero.pill": "Today's journey · {mode} day",
  "hero.title": "You are making a beautiful impact",
  "hero.progress": "Completed {c} of {t} today. Keep going — consistency wins.",
  "hero.pct": "Today's progress",
  "hero.points": "blessing points",
  "hero.done": "done",
  "mode.full": "Full",
  "mode.normal": "Normal",
  "mode.busy": "Busy",
  "mode.travel": "Travel",
  "mode.sick": "Sick",
  "mode.title": "How's your day looking?",
  "mode.sub": "Match it to your energy.",
  "mode.focus": "◉ Focus",
  "focus.quit": "× End focus",
  "focus.eyebrow": "One moment suffices",
  "focus.q": "Did you pray Witr today?",
  "focus.sub": "One rak'ah could be your day's finest seal.",
  "focus.logged": "✓ Witr logged",
  "focus.cta": "Log Witr now",
  "tools.now": "Now",
  "tools.nowSub": "What fits this moment",
  "tools.min": "Today's minimum",
  "tools.minSub": "No-pressure essentials",
  "tools.start": "Start now",
  "tools.startSub": "Still plenty of good left",
  "tools.custom": "Custom",
  "tools.customSub": "Add your own",
  "tools.customAsk": "Custom act name:",
  "rescue.eyebrow": "Today's rescue plan",
  "rescue.title": "One small step, huge impact",
  "rescue.sub": "You don't need it all. Pick what fits now.",
  "rescue.one": "One act now",
  "rescue.oneTitle": "Morning adhkar",
  "rescue.oneSub": "Two minutes to light your morning.",
  "rescue.oneDone": "✓ Logged",
  "rescue.oneGo": "Start now ←",
  "rescue.quran": "Quran session",
  "rescue.quranPages": " · {n} pages today",
  "rescue.quranDone": "Well done, session complete",
  "rescue.quranStart": "Start a Quran session",
  "rescue.quranAsk": "How many pages did you read?",
  "rescue.quranLive": "Session ongoing",
  "rescue.quranBegin": "Start session",
  "rescue.min": " min",
  "rescue.focusBtn": "Focus till prayer",
  "rescue.record": "Log prayer",
  "rescue.recorded": "✓ Logged",
  "rescue.prep": "Getting ready",
  "rescue.prepSub": "20 minutes to Asr · time for wudu?",
  "ramp.eyebrow": "Gradual wird",
  "ramp.full": "Week two · two pages daily",
  "ramp.light": "Light mode · one page daily",
  "ramp.sub": "Slow and steady. Pause or ease off anytime.",
  "ramp.ease": "Ease off",
  "ramp.restore": "Restore",
  "intent.eyebrow": "Before work or study",
  "intent.q": "Your intention now?",
  "intent.edit": "Edit intention",
  "intent.ask": "Your intention today?",
  "intent.job": "Halal provision",
  "intent.craft": "Excellence",
  "intent.benefit": "Benefiting others",
  "intent.learn": "Learning",
  "intent.family": "Supporting family",
  "friday.eyebrow": "Friday companion",
  "friday.soon": "· upcoming plan",
  "friday.now": "· today",
  "friday.titleSoon": "Your Friday wird awaits",
  "friday.titleNow": "Blessed Friday — your wird awaits",
  "util.fav": "Favorites",
  "util.forget": "Don't forget",
  "util.tawbah": "Repentance journal",
  "util.tawbahNeed": "I need istighfar today",
  "util.tawbahDone": "✓ Done",
  "util.tawbahGo": "Log it",
  "moment.next": "Next prayer",
  "moment.setTimes": "Set your times",
  "moment.setTimesSub": "From Account → prayer times",
  "moment.remind": "Remind me",
  "moment.remindOn": "✓ You'll be reminded",
  "moment.mosque": "🕌",
  "moment.mosqueTitle": "Mosque mode: silences reminders",
  "moment.niyyah": "Today's intention",
  "tasbeeh.title": "Quick dhikr counter",
  "tasbeeh.done": "✓ Complete",
  "sec.dailyEyebrow": "Your daily wird",
  "sec.daily": "Prayers & litanies",
  "filter.all": "⌄ All",
  "filter.done": "✓ Done",
  "filter.todo": "○ Remaining",
  "sec.extrasEyebrow": "Beyond prayer",
  "sec.extras": "Quran & good deeds",
  "sec.moreDetail": "Small act, huge impact",
  "quran.eyebrow": "Daily Quran",
  "quran.of": "of",
  "quran.page": "pages",
  "quran.full": "MashaAllah, today's wird complete. Add more if you wish.",
  "quran.next": "Next step: finish {n} pages.",
  "quran.add": "Add page +",
  "quran.plan": "View plan",
  "adhkar.eyebrow": "Scattered adhkar",
  "adhkar.title": "Remember Allah through your day",
  "adhkar.sub": "Short supplications for a present heart.",
  "dua.eyebrow": "Your private space",
  "dua.title": "Today's dua",
  "dua.add": "+ Add a heartfelt dua",
  "dua.ask": "Write a heartfelt dua:",
  "dua.rE": "Your dua today",
  "dua.rT": "O Allah, grant my parents health and wellness",
  "dua.rS": "For parents",
  "dua.rB": "I made dua today",
  "dua.rDone": "✓ Made dua today",
  "gentle.eyebrow": "Gentle reminder",
  "gentle.title": "Every day is a new start",
  "gentle.sub": "Missed something? No harm. Pick one small act now.",
  "gentle.week": "This week",
  "gentle.witr": "Witr 5 days",
  "goals.eyebrow": "Goals at your pace",
  "goals.title": "Your spiritual journey",
  "goals.add": "+ Add goal",
  "goals.ask": "New goal name:",
  "goals.newDetail": "New goal · start tiny",
  "goals.new": "New",
  "goals.witr": "Witr this week",
  "goals.witrSub": "3 days left",
  "goals.quran": "Monthly Quran",
  "goals.quranSub": "24 of 60 pages",
  "goals.kin": "Kinship",
  "goals.kinSub": "Weekly gentle goal",
  "night.eyebrow": "Before sleep",
  "night.title": "End your day in peace",
  "night.sub": "Wudu, sleep adhkar, Ayat al-Kursi, one gratitude, then Fajr intention.",
  "night.cta": "Start night routine ←",
  "night.journalEyebrow": "Private reflection",
  "night.journalQ": "What was your finest moment today?",
  "night.journalPh": "Write yourself something kind…",
  "night.journalNote": "Yours alone — excluded from stats.",
  "footer.verse": "﴿ وَاذْكُر رَّبَّكَ كَثِيرًا وَسَبِّحْ بِالْعَشِيِّ وَالْإِبْكَارِ ﴾",
  "minplan.title": "Minimum plan active",
  "minplan.sub": "Prayers, short dhikr, one verse, 10 istighfar, and Witr. Enough for today.",
  "minplan.cancel": "Cancel",
  "now.eyebrow": "What fits right now",
  "now.title": "After Fajr, a blessed start",
  "now.sub": "Just four steps. Take what's easy.",
  "now.done": "✅ Done",
  "now.partial": "◐ Partial",
  "now.later": "↷ Later",
  "now.foot": "Still much good left in the day.",
  "now.add": "+ Add act",
  "zk.title": "Remember Allah",
  "zk.close": "Close",
  "ac.account": "Account",
  "ac.niyyah": "My weekly intention",
  "ac.customize": "Customize devotions",
  "ac.qiyam": "Night mode",
  "ac.remind": "Gentle reminders",
  "ac.privacy": "Privacy & data",
  "ac.newdayT": "A new day, a fresh start",
  "ac.newdayS": "Start fresh whenever you need.",
  "ac.newdayB": "New day",
  "bk.t": "Backup & privacy",
  "bk.s": "Your data stays on your device — no servers. Export or restore anytime.",
  "bk.enc": "Encrypted export",
  "bk.plain": "Plain export",
  "bk.imp": "Import",
  "bk.wipe": "Erase all",
  "bk.passAsk": "Encryption password (keep it — unrecoverable without it):",
  "bk.impAsk": "Encrypted backup password:",
  "bk.wipeAsk": "Erase all Wird data from this device?",
  "bk.count": "Exported ({n} items). Keep the file safe.",
  "bk.okEnc": "Encrypted backup exported (AES-GCM).",
  "bk.restored": "Restored ({n} items). Refresh to see your data.",
  "bk.bad": "Invalid file or wrong password.",
  "bk.fail": "Export failed. Check storage.",
  "bk.noenc": "Encryption unavailable in this browser.",
  "bk.wiped": "All data erased. Refresh to start over.",
  "bk.wipeFail": "Erase failed.",
  "rm.t": "Local reminders",
  "rm.s": "On-device only. Auto-silenced in mosque mode.",
  "rm.on": "✓ On",
  "rm.off": "Enable",
  "rm.bed": "Review",
  "rm.gentle": "Gentle",
  "rm.bal": "Balanced",
  "rm.strict": "Strict",
  "rm.test": "Test",
  "rm.testT": "Test works 🔔",
  "rm.testB": "Your reminders will look like this.",
  "rm.sent": "Test notification sent.",
  "rm.noperm": "Enable browser notifications first.",
  "pt.t": "Prayer times (manual)",
  "pt.s": "Powers countdowns and smart ordering. Leave empty for default.",
  "ap.t": "Appearance & language",
  "ap.s": "Pick theme and language.",
  "ap.light": "Light",
  "ap.dark": "Dark",
  "ap.oled": "Black",
  "rv.heroE": "Today's harvest · one minute before sleep",
  "rv.heroT": "How was your day?",
  "rv.heroS": "Everything logged is pre-checked — confirm and correct.",
  "rv.heartE": "Heart check",
  "rv.heartT": "How did you live today?",
  "rv.r1": "Held my anger today",
  "rv.r2": "Guarded my tongue",
  "rv.r3": "Honored my parents",
  "rv.r4": "Was honest at work",
  "rv.r5": "Did a kindness",
  "rv.r6": "Slept early for Fajr",
  "rv.mGood": "Bright",
  "rv.mOk": "Okay",
  "rv.mLow": "Tired",
  "rv.gratPh": "One blessing you're grateful for…",
  "rv.gratAria": "Today's blessing",
  "rv.submit": "Seal your day 🌙",
  "rv.score": "Your score",
  "rv.pts": "pts",
  "rv.edit": "Review again",
  "rv.stDone": "✓ Done",
  "rv.stPart": "◐ Partial",
  "rv.stMiss": "○ Missed",
  "rv.g85": "A radiant day 🌟",
  "rv.g60": "A steady day 🤍",
  "rv.gLow": "May Allah accept 🤲",
  "rv.pagesT": "Quran wird",
  "rv.pagesD": "{p} of {g} pages",
  "rv.fastT": "Fasting",
  "rv.fastOn": "{f}",
  "rv.fastOff": "Not fasting",
  "rv.tasT": "Quick dhikr",
  "nw.i1t": "Fajr prayer",
  "nw.i1d": "On time · congregation",
  "nw.i2t": "Post-prayer adhkar",
  "nw.i2d": "Two quiet minutes",
  "nw.i3t": "Morning adhkar",
  "nw.i3d": "6 of 10",
  "nw.i4t": "Quran wird",
  "nw.i4d": "2 of 4 pages",
  "du.feat": '"O Allah, help me remember You, thank You, and worship You well."',
  "ins.heroE": "Progress from your data — no guessing",
  "ins.heroT": "Quiet steps make an impact",
  "ins.heroS": "Pick a period to reflect on, no comparison, no blame.",
  "ins.p0": "Today",
  "ins.p1": "Last 7 days",
  "ins.p2": "2 weeks",
  "ins.p3": "This month",
  "ins.p4": "3 months",
  "ins.p5": "Season",
  "ins.p6": "Year",
  "ins.avg": "Your average",
  "ins.avgS": "In this period",
  "ins.witr": "Witr nights",
  "ins.witrS": "A steady habit",
  "ins.pages": "Quran pages",
  "ins.pagesS": "Period total",
  "ins.streak": "Streak",
  "ins.streakS": "consecutive days",
  "ins.coach": "Your coach ✦",
  "ins.warm": "Log more days to unlock expert analysis — 14 days minimum.",
  "ins.chartE": "Period view",
  "ins.chartT": "Daily completion",
  "ins.chartEmpty": "No data yet — start logging today.",
  "ins.radarE": "Week balance",
  "ins.radarT": "Where does each gate stand?",
  "ins.stripT": "Last 30 days",
  "yr.title": "Hijri year in review",
  "yr.days": "active days",
  "yr.pages": "pages",
  "yr.score": "Avg score",
  "yr.witr": "witr nights",
  "yr.best": "Best month",
  "yr.streak": "Longest streak",
  "ins.noData": "No data",
  "ins.week": "Week",
  "cat.salah": "Prayer",
  "cat.quran": "Quran",
  "cat.dhikr": "Dhikr",
  "cat.knowledge": "Knowledge",
  "cat.character": "Character",
  "cat.family": "Family",
  "br.risk": "at risk tonight",
  "br.neglect": "missed {n} straight days",
  "br.pace": "Quran pace down {d}% ({n} vs {p} pages/day)",
  "br.liftA": "Days with",
  "br.liftB": "lift the rest +{n}",
  "br.protect": "Protect this first",
  "cal.title": "Your quiet journey",
  "cal.sub": "Tap any day to recall it.",
  "cal.excellent": "Excellent",
  "cal.good": "Good",
  "cal.partial": "Partial",
  "cal.season": "Occasion",
  "cal.fridayNote": "Next Friday",
  "cal.fridaySub": "Al-Kahf · Salawat · early arrival",
  "cal.add": "Add to Friday plan",
  "cal.added": "✓ Added",
  "cal.dayNote": "Day {d}: log your wird from Today; progress saves here.",
  "cal.white": "White days",
  "cal.friday": "Friday",
  "lb.adhkar": "Adhkar",
  "lb.quran": "Quran",
  "lb.hadith": "Hadith",
  "lb.paths": "Paths",
  "lb.dreams": "Dreams",
  "qr.search": "Search verses or surahs…",
  "qr.searchAria": "Search Quran",
  "qr.fontDown": "Smaller",
  "qr.fontUp": "Larger",
  "qr.noRes": "No results — try another word.",
  "qr.surahAria": "Choose surah",
  "qr.mark": "Bookmark here",
  "qr.mem": "Memorized",
  "qr.markLine": "Bookmark",
  "qr.memCount": "memorized",
  "qr.loading": "Opening mushaf…",
  "qr.failT": "Couldn't load mushaf",
  "qr.failS": "Connect once — then it works offline.",
  "qr.retry": "Retry",
  "hd.search": "Search selections…",
  "hd.searchAria": "Search hadith",
  "hd.noRes": "No results — try another word.",
  "hd.nawawi": "Forty Nawawi",
  "hd.nawawiNote": "Selections from the Forty — concise, memorable.",
  "hd.fav": "★ Favorites",
  "hd.favEmpty": "No favorites yet — tap ☆ on any hadith.",
  "hd.curated": "Famous selections; consult printed editions for full texts.",
  "hd.favAria": "Favorite",
  "pa.add": "Add your book",
  "pa.ask": "Book you're reading:",
  "pa.mine": "Your book",
  "dr.empty": "No dreams yet. Big dreams start with one small step.",
  "dr.add": "Record dream",
  "dr.new": "+ New dream",
  "dr.askT": "Your big dream? (e.g. Hajj 2028)",
  "dr.askTar": "Target date?",
  "dr.askStep": "Next step?",
  "dr.askFirst": "First tiny step today?",
  "dr.del": "Delete dream?",
  "dr.delAria": "Delete dream",
  "dr.stepNew": "+ New step",
  "ret.absent": "We missed you · {n} days away",
  "ret.title": "The door is open — return now",
  "ret.back": "Start anew 🤍",
  "ret.continue": "Continue normally",
  "kd.title": "Kids' corner",
  "kd.emptyT": "Fun challenges for your kids",
  "kd.emptyS": "5 daily star quests — add your child.",
  "kd.add": "Add child",
  "kd.ask": "Child's name?",
  "kd.q1": "Fajr",
  "kd.q2": "Quran page",
  "kd.q3": "33 tasbih",
  "kd.q4": "Good deed",
  "kd.q5": "Early sleep",
  "pg.add": "+ New pledge",
  "pg.askT": "Your pledge? (e.g. Fajr at mosque 7 days)",
  "pg.askS": "Stake if you slip? (e.g. $5 charity)",
  "pg.del": "Delete pledge?",
  "pg.delAria": "Delete",
  "pg.stake": "Stake",
  "pg.days": "kept days",
  "pg.checkAria": "Today kept",
  "qd.title": "Making up",
  "qd.empty": "None owed — mashaAllah",
  "qd.open": "{n} prayers owed",
  "qd.clear": "Made up ✓",
  "qd.clearDone": "Clear done",
  "qd.delAria": "Delete",
  "fs.title": "Today's fast",
  "fs.off": "Not fasting today",
  "fs.t0": "Ramadan fard",
  "fs.t1": "Nafl",
  "fs.t2": "Makeup",
  "fs.t3": "White days",
  "fs.t4": "Vow",
  "br.title": "Breaking a habit",
  "br.pick": "Pick a habit to quit today",
  "br.start": "+ Start",
  "br.clean": "clean days 🔥",
  "br.slips": "Recorded slips",
  "br.log": "Log a slip (and repent)",
  "br.end": "End",
  "br.ask": "Which habit to quit?",
  "br.delAsk": "Delete breaker?",
  "ch.new": "+ New challenge",
  "ch.askT": "Challenge name:",
  "ch.askD": "How many days?",
  "ch.del": "Delete challenge?",
  "ch.delAria": "Delete",
  "ch.checkAria": "Log today",
  "ch.days": "days",
  "rm2.title": "Ramadan Kareem — may Allah accept",
  "rm2.sub": "Taraweeh awaits tonight.",
  "rm2.tr": "Log Taraweeh",
  "rm2.trDone": "✓ Taraweeh done",
  "rm2.fast": "Fasting today",
  "ad.g1t": "Morning",
  "ad.g1d": "Begin in peace",
  "ad.g2t": "After prayer",
  "ad.g2d": "Short post-prayer adhkar",
  "ad.g3t": "Evening & sleep",
  "ad.g3d": "End in tranquility",
  "ad.g4t": "Daily moments",
  "ad.g4d": "Travel, food, mosque, home",
  "ad.heroE": "Adhkar on time",
  "ad.heroT": "Remember Allah through your day",
  "ad.heroS": "Pick what fits your moment.",
  "ad.cfE": "Today's wird",
  "ad.cfT": "Salawat",
  "ad.cfS": "100 times • keep it with you",
  "ad.cfDone": "Done · restart",
  "ad.cfGo": "Start counter",
  "cm.del": "Delete?",
  "dm.t": "Demo mode",
  "dm.s": "Fill the app with 45 days of sample data to see stats and coach instantly.",
  "dm.seed": "Load demo",
  "dm.clear": "Clear demo",
  "dm.ok": "Loaded {n} days. Refresh.",
  "dm.cleared": "Demo cleared.",
  "dm.warn": "Won't touch your data — only empty days fill.",
  "ins.share": "Share progress",
  "ins.shared": "Shared ✓",
  "ins.downloaded": "Image saved ✓",
  "ins.shareFail": "Share failed",
  "pwa.install": "Install app",
};

export function tr(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  const dict = lang === "ar" ? AR : EN;
  let s = dict[key] ?? AR[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v));
  return s;
}
